### ISSUE TITLE
Add unit tests for Profiler

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#252]
Even if we don't test the Profiler graphs, we can still test:
- [x] (#258) Renderer interface collecting profiling data
- [x] (#258) `ProfilerCache` returning promises that resolve to the collected data
- [x] (#258) Various chart builds generate reasonable data
